version: '2.7'
services:
  app:
    container_name: application
    image: nextcloud:apache
    environment:
     - POSTGRES_HOST=db
     - POSTGRES_PASSWORD=/run/secretsnextcloud
     - POSTGRES_DB=nextcloud
     - POSTGRES_USER=nextcloud
    ports:
      - 80:80
    volumes:
      - data:/var/www/html
    networks:
      - mynat 
  db: 
    container_name: database
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=/run/secrets/nextcloud
      -  POSTGRES_DB=nextcloud 
      - POSTGRES_USER=nextcloud
    
    volumes: 
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - mynat
volumes:
  db_data: 
  data: 
networks:
  mynat:
secrets:
  nextcloud:
    file: next.txt
      
  


  