version: '2.7'
services:
  minecraft: 
   container_name: minecraft
   image: itzg/minecraft-server
   ports:
     - 25565:25565
   environment: 
    EULA: 'TRUE'
   deploy: 
    resources:
      limits:
        memory: 1.5G
   volumes: 
    - "~/minecraft:/data"